# Generated by Django 4.2.22 on 2025-06-06 13:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, choices=[('mr', 'Mr.'), ('mrs', 'Mrs.'), ('ms', 'Ms.'), ('dr', 'Dr.'), ('prof', 'Prof.')], max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('identification_type', models.CharField(blank=True, max_length=50)),
                ('identification_number', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('preferences', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('alternate_phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('id_type', models.CharField(blank=True, max_length=50)),
                ('id_number', models.CharField(blank=True, max_length=100)),
                ('id_expiry_date', models.DateField(blank=True, null=True)),
                ('preferred_room_type', models.CharField(blank=True, max_length=100)),
                ('dietary_restrictions', models.TextField(blank=True)),
                ('special_requests', models.TextField(blank=True)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('newsletter_subscription', models.BooleanField(default=False)),
                ('is_vip', models.BooleanField(default=False)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('blacklist_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='GuestPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_floor', models.CharField(blank=True, max_length=20)),
                ('preferred_view', models.CharField(blank=True, max_length=100)),
                ('smoking_preference', models.CharField(choices=[('smoking', 'Smoking'), ('non_smoking', 'Non-Smoking')], default='non_smoking', max_length=20)),
                ('housekeeping_frequency', models.CharField(choices=[('daily', 'Daily'), ('every_other_day', 'Every Other Day'), ('weekly', 'Weekly')], default='daily', max_length=20)),
                ('wake_up_call', models.BooleanField(default=False)),
                ('newspaper_delivery', models.BooleanField(default=False)),
                ('wheelchair_accessible', models.BooleanField(default=False)),
                ('hearing_impaired', models.BooleanField(default=False)),
                ('visually_impaired', models.BooleanField(default=False)),
                ('other_accessibility_needs', models.TextField(blank=True)),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_preferences', to='guests.guest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GuestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('drivers_license', "Driver's License"), ('national_id', 'National ID'), ('visa', 'Visa'), ('other', 'Other')], max_length=20)),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('issuing_authority', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(upload_to='guest_documents/')),
                ('notes', models.TextField(blank=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='guests.guest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['email'], name='guests_gues_email_e4fe59_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['phone'], name='guests_gues_phone_6b6426_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['last_name', 'first_name'], name='guests_gues_last_na_682095_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['is_vip'], name='guests_gues_is_vip_fef844_idx'),
        ),
    ]
